"""Add inventory and fraud fields

Revision ID: 22280d015df2
Revises: f01cc5e36458
Create Date: 2026-09-05 12:37:08.600528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22280d015df2'
down_revision: Union[str, Sequence[str], None] = 'f01cc5e36458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('average_unit_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('transactions', sa.Column('cost_of_goods_sold', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
    op.add_column('transactions', sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
    op.add_column('transactions', sa.Column('is_anomaly', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_anomaly')
    op.drop_column('transactions', 'gross_profit')
    op.drop_column('transactions', 'cost_of_goods_sold')
    op.drop_column('inventory_items', 'average_unit_cost')
    # ### end Alembic commands ###
